version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    networks:
      - testtask
  testapi:
    env_file:
      - ./.env
    links:
        - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    command: yarn start:docker
    ports:
      - "80:3000"
    depends_on:
      - postgres
    networks:
      - testtask
networks:
  testtask:
